<?php
/**
 * @file
 * Module to supply social media icons for ASC Sites.
 */

/**
 * @defgroup asc_socialmedia
 * Module to supple field to add OPIC image.
 *
 * And finally, our module defines the widet in
 * opic_field_widget_info() and field_example_field_widget_form().
 * The widget is the form element used to receive input from the user
 * when the field is being populated.
 *
 * @see field_types
 * @see field
 */

/**
 * Implements hook_menu().
 *
 * Provides a simple user interface that tells the developer where to go.
 */
function asc_socialmedia_menu() {
  $items['admin/config/asc_socialmedia'] = array(
    'title' => 'ASC Social Media',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('asc_socialmedia_form'),
    'access arguments' => array('administer asc_socialmedia'),
  );
  return $items;
}

/**
 * Implements hook_init
 */
function asc_socialmedia_init() {
  drupal_add_css(drupal_get_path('module', 'asc_socialmedia') . '/asc_socialmedia.css');
  drupal_add_js(drupal_get_path('module', 'asc_socialmedia') . '/asc_socialmedia_sharing.js');
}

/*
 * Implements hook_permission()
 */
function asc_socialmedia_permission() {
  return array(
    'administer asc_socialmedia' => array(
      'title' => t('Administer ASC Social Media'),
      'description' => t('Update sitewide social media settings.'),
    ),
  );
}

/**
 * Admin form for asc socialmedia.
 */
function asc_socialmedia_form($form_state) {
  $form = array();
  $sites = asc_socialmedia_get_services();

  foreach ($sites as $site => $icon) {
    $form[$site] = array(
      '#title' => $site,
      '#description' => "Please enter the URL for this organization's profile associated with " . $site,
      '#type' => 'textfield',
      '#default_value' => variable_get('asc_socialmedia_url_' . $site),
    );
  }

  $form['submit'] = array(
    '#type' => 'submit', 
    '#value' => t('Save'),
  );
  return $form;
}

function asc_socialmedia_get_services() {
  $sites = array(
    'Facebook' => 'facebook.png',
    'Twitter' => 'twitter.png',
    'YouTube' => 'youtube.png',
    'Blogger' => 'blogger.png',
    'Flickr' => 'flickr.png',
    'Google_Plus' => 'googleplus.png',
    'Issuu' => 'issuu.png',
    'iTunes' => 'itunes.png',
    'Linked In' => 'linkedin.png',
    'Pinterest' => 'pinterest.png',
    'rss' => 'rss.png',
    'Tumblr' => 'tumblr.png',
    'Vimeo' => 'vimeo.png',
    'Wordpress' => 'wordpress.png',
    'Give' => 'give.png',
  );
  return $sites;
}

function asc_socialmedia_contact_fields() {
  $fields = array(
    'Address_1',
    'Address_2',
    'City',
    'State',
    'Zip',
    'Phone',
    'Fax',
    'Link_1_Text',
    'Link_1_URL',
    'Link_2_Text',
    'Link_2_URL',
    'Link_3_Text',
    'Link_3_URL',
  );
  return $fields;
}

/**
 * Form submission
*/
function asc_socialmedia_form_submit(&$form, &$form_state){
  $sites = asc_socialmedia_get_services();
  foreach ($sites as $key => $value) {
   variable_set('asc_socialmedia_url_' . $key, $form_state['values'][$key]);
  }
  drupal_set_message('Your settings have been saved.');
}

/*
 * Implements hook_block_info
 */

function asc_socialmedia_block_info() {
  $blocks['asc_socialmedia'] = array(
    'info'        => 'ASC Social Media Icons',
    'weight'      => '-10',
    'region'      => 'footer_third',
    'status'      => 'true',
    'cache'       => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['asc_socialmedia_sharing'] = array(
    'info'        => 'ASC Sharing Icons',
    'weight'      => '50',
    'region'      => 'content',
    'status'      => 'true',
    'cache'       => DRUPAL_CACHE_PER_PAGE,
  );
  return $blocks;
}

/*
 * Implements hook_block_view
 */

function asc_socialmedia_block_view($delta = '') {
  switch($delta){
  case 'asc_socialmedia':

    $block['subject'] = '';
    $block['content'] = '';

    $sites = asc_socialmedia_get_services();

    foreach ($sites as $site => $icon) {
      $url = variable_get('asc_socialmedia_url_' . $site);
      if ($url != '') {
        $image = theme_image(
          array(
            'path' => drupal_get_path('module', 'asc_socialmedia') . '/icons/' . $icon,
            'alt' => $site . ' profile',
            'title' => $site . ' profile',
            'attributes' => '',
          )
        );
        $block['content'] .= '<a href="' . $url . '">' . $image . '</a>';
      }

    }
    
    break;

  default:
    $block['subject'] = '';
    $block['content'] = theme('asc_socialmedia_sharing', '');

    break;
  }

  return $block;
}

/*
 * Implementation of hook_theme()
 */
function asc_socialmedia_theme() {
  return array(
    'asc_socialmedia_sharing' => array(
      'template' => 'asc_socialmedia_sharing',
    ),
  );
}
